- name: Stop mongod service
  systemd:
    name: mongod
    state: stopped

- name: Remove mongo packages
  apt:
    name: "{{ item }}"
    purge: yes
    state: absent
    autoremove: yes
  loop:
    - "mongodb-org"
    - "mongodb-org-server"
    - "mongodb-org-shell"
    - "mongodb-org-mongos"
    - "mongodb-org-tools"

- name: Remove APT Key
  apt_key:
    url: https://www.mongodb.org/static/pgp/server-{{ mongodb_version }}.asc
    state: absent

- name: Remove Repo
  apt_repository:
    repo: "deb [ arch=amd64,arm64,aarch64 ] https://repo.mongodb.org/apt/{{ ansible_distribution|lower }} {{ ansible_distribution_release }}/mongodb-org/{{ mongodb_version }} multiverse"
    update_cache: true
    state: absent

- name: Remove sources file
  file:
    path: "/etc/apt/sources.list.d/repo_mongodb_org_apt_ubuntu.list"
    state: absent

- name: Remove MongoDB Databases and Logs
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "/var/log/mongodb"
    - "/var/lib/mongodb"

- name: Remove Python packages
  pip:
    name: "{{ item }}"
  loop:
    - "pymongo"
