---
- name: Get current host ip address
  set_fact:
    host_ip: "{{ ansible_default_ipv4.address }}"

- name: Configure static IP in /etc/dhcp/dhclient.conf
  lineinfile:
    dest:  /etc/dhcp/dhclient.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - { regexp: "^interface eth[0-9]$", line: "interface {{ interface }}" }
    - { regexp: "^static ip_address", line: "static ip_address={{ host_ip }}" }
    - { regexp: "^static routers", line: "static routers={{ router_ip }}" }
    - { regexp: "^static domain_name_servers", line: "static domain_name_servers={{ dns_server }}" }
  notify: reboot
